apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:egI/Wk7cPx9I6KmOITkAb/gvSgm9smFgMC6NCGBgGYlA8oX9ONe2zw==,iv:ulbqWiZYEmV1UiPARehN7sQdOfLYbYQM8TUjARlWJwo=,tag:HlGaEexLiMzuBDqhJifuGw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10e04afnhnka5steqvjnug2zylp3ng0rjzv765pkv47c8megcg9hs8w7rdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUzBkY0p5WE9RZzRucVpB
            Um9GYWkzYkRXYUZOQUlETGRnRm54dTdwS3pBCjdxRjRHdUttREF2QnZBT1I2LzR0
            M2xIQ1FKczJlbmZrR2Fmem5LQ0lLS2sKLS0tIHNZRHFldTR6YThpcFFwZ0hQaHZK
            Z0QxTm5vZlRBM1lCNDRKL2VHbVI2a1kKrWolHSXYqoYP+6uiGQ6nOGXKZOQPZUAn
            oZj8bRxzoKjjOnLiTGiWm72fOAeF6SNLyC1oYXChLBXYXOR4zNaUzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T06:33:46Z"
    mac: ENC[AES256_GCM,data:9/9UhOWKilbhaCZ6DGjFjtW7lFAukCSSeP2yeydQdTH4hUWseoukXa8eRuY4v2xhQAGnM9hQiNd5CGiBzFk5jkRgF6ONvwa52DxC3t/HKD7pNyFvNsq1WzuXQCiUYOj74N3am+ZdTlChrg7l0vPJLfMRVG4X5FKOhPQSrcEyKK0=,iv:2oQaTzMtnp7oFUKxCghxAVrQYe1lM03FyYy5YroccXg=,tag:OJp91szDnauGlN+fC2E2Rw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
