apiVersion: v1
kind: Secret
metadata:
  name: webhook-token
  namespace: flux-system
stringData:
  token: ENC[AES256_GCM,data:9BA8mtW4tSiiHccLcGGmK+E9rvwi8NpUQxylg6jMnt7Yy3PtfUMf3Q==,iv:5Ji7Zy5E8Ogo2ZbGr+NbEp9QSoKiI6tRrR3BlUD1W00=,tag:GKGb0NKcqN4FK65h6oyXJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSW9USlBnYjN4dmI0RExL
        WmJtWXg4T1dMNkFVYi9DSGhkT3F3dUVvR1ZBCjJzemlBMFpOZEpFeW5GTTZVTEpk
        RHVDYlpRRkdqSTE0RXJhNEttM082Uk0KLS0tIGNBM21RMDNBRzRSRjgzbVBDSFVi
        dEd1YStYaEFsM1VYRXE0N1Rsa1RsRjQKzjLFoa9vL8SmdZHD9ohcReqN7CBDQ4wH
        p5qaHnDHAa3okZVwnQUBpjN5cdqm2xGamD6F7Piun4sjrkVS1okuAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jqaxewhvdms0a4xnzz2frg4ywc8ll3wy7pyyqye7v2eddwwf298qpcm4hp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T17:16:16Z"
  mac: ENC[AES256_GCM,data:qOQGgmPvm2c1MDH4QcF4VnzNasdianX7fL7ksaicg18+JIfVfS3WkjIEsXO6uiYhuw4dGfNGMrEogDBNjA4gM6p/25N+eJSNVvxX3HyvwCNXiwFQAFLdGA3Iv3+zosaj20pdaICwqh0EueMxSnNa9rGo2VxChLWFZfTn1TrOqIY=,iv:NIQ7UAxSboxDahGAVrAwt5x8t7ZmD7oLJtcIzRWPwgY=,tag:VHRYhLyq801fWQilXJQuuQ==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
