apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1FN7fYM+tIeMUdrGUwjjYWF/N2Lj4bcy1tyheJBNUhL7WfbkgdsX9w==,iv:HcoVHtvGhFkJUSwWTqLBnRMh+ayd/04FEKoingSTXQg=,tag:Xu/Y02l88GdxGTX6hE5zGw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WjdnQmdQTnNCMk1vN01x
            K1ZlYkliYWxwdFdqdmp0SUQ2TFJxcEVsQkhRClRuSmFSbTRiblpoQzdaNjdyV3NH
            V0g3Y0JaanQzWGI1T2RhWm14QzdnbkEKLS0tIFBhVFlBVDhreUtjNFU0V1YxeXRz
            b0hod0hkcW50ZVNjNTFiYXJ3STcwZ00K79E/1v1LtOvT09uUx3nDWB5gfsw9XUhx
            nTVM/C4fygFkpilxwlk1hlTfm71eBATvcs3lWdoG/DXc4aQhxRD6Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T07:46:46Z"
    mac: ENC[AES256_GCM,data:82n9EzwDMK3ZeWQN6envzOpwZc7EDxdgiHCfazvBAq9JmZNkEDStGfcI5IQlPdCHYx3QES8xccfVhNYPg8FAQz+wybeOCbN+VcLATQhd38aKVnzEpUZSD+MM3H1DE7D2JAQbkALgV7TXzLH0BpVFAM7vNHLK+3tFJqP94JeWj2g=,iv:v3dRZv22qk9qDd4WYDVnOvmJyaUB+1wqOpRQJNXSWCo=,tag:yWdOb/CxT8LrXhLzxIodIA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
