apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:SIBb6BD8762Nib7GGX4TgFBC0PGNFp3x1nRgPCR4cOXvIlOITpZiwyYidxiMHLlyO5cwQAi2RxaM8DuB9n+vgsQ=,iv:WUPGs/N16VFfg7DeNTXCpE9i8jwBEXhOP1G60M8dyAQ=,tag:1+AXyzzrdGmqPz/SBEGzkA==,type:comment]
    #ENC[AES256_GCM,data:mbmOP1L2iF8OQNz8uxVe3uavw8Q8RJdk5WfGfoD2i64OIhKsnyXsqTD8AJY=,iv:YiudUXP/tTyeMZ6arKlODr7yoUWndu14DW02k8NjM1I=,tag:79txmpr8ou7dN3dsDUKMpw==,type:comment]
    VIP: ENC[AES256_GCM,data:TLl1ly5qUpBETMTg,iv:QdbZWUdRFRI6neg6NhPG3pVO0lAiGtv/YRzC1RMaBYM=,tag:FlRTOPDjggmg8xTnGRc2AQ==,type:str]
    #ENC[AES256_GCM,data:JQRlBxDotqk9ag/GwOCefOUTI8TWCjJXzKg=,iv:1ohyVJtnJCDtEhMOQelUgmx1ZkPQCIHhGeYbEsS6EN8=,tag:2GDhzmNGq+lhNwq/JdOtPg==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:ID+4UKDW6pUvVVdz,iv:4vtlaMJVtQnSE5GnpDqPLEpwOq21trGBZr7TP2rjLBQ=,tag:bVnDEq/jgfkwBY8B+6qKkA==,type:str]
    #ENC[AES256_GCM,data:Ba25pkBz2IgVZK1xKaqBPcQWpBYFyhKRp50Jkc953nSEJQ==,iv:PpOW1to61Y9daNrTOFuWQ/49UrfSxRx9Z/klx5gYJY4=,tag:i4YFjjKY3NvxfF3HmFbwYQ==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:KTJMuWCpXVtxFzk=,iv:F0lfug5gA455QPR7blvfXbAd/6CG7/1kpM+9Gw1cWEc=,tag:KNNTlRyDXRCXmynGGyfi+A==,type:str]
    #ENC[AES256_GCM,data:9oqUiAMg1GLJYeKOl/6A1Np6e/IY2NMplGuQn+rsrEZsDdaiuQPn0BFKepDT/SM=,iv:JIL+CDqrZex08NKBoZ7EK9C/ddYdNUTvaFcLJGdWtCM=,tag:kw3SRITx+u7imqHF64VSuA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:EAJ6+S+Kx2qg+DVlmMDUeFXOnN2ZBDte8P4=,iv:4web5i+gkeHGzAk5pnA7I1c/PkDs1TQmhUsGvSkfVHM=,tag:MjOB7RV/JIHm6H+AAvXkGg==,type:str]
    #ENC[AES256_GCM,data:95sUHTmjSAGPvW0J5WsbqAFQl0QiT8/brd2GQFoylNA5Gz8WqIlEtVfqK9IfEYVh2OJegYZ4CcWqJqLR0yMMFziN+KjK+IS9XCbCZaN5cV8=,iv:lw0vwWqfs8HXEl4wAZ7NnvBlGfav7BUZvxAt5KMlwno=,tag:x2oejCVO1X/2dgBQ1yKvWg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:Uw8XsZM3tlI6jvsh,iv:aM2XyOrnHFa7o+Se8BpE4r81Pd6OifUfjakGaLgG1hs=,tag:glWl4cejxFnIWvkVO41D3w==,type:str]
    #ENC[AES256_GCM,data:FOewxfbxQlyHWRCRfEtq9chOABI3zMwdmGC+02KZX+cOqD0l/KSq11Oxz6/YVPtZXyJT4zXZ3BQ=,iv:pSeJmnpaekyT9sjpoFtO/CBFPF8XQzy4Rawuk1rL1bU=,tag:EAhv17KJ7vjkbh2FRL7mXA==,type:comment]
    #ENC[AES256_GCM,data:YuddQYNVqJLXlSQUqQ8zP263IiDOTxvu8w==,iv:tgocQWQwpU4lZCCck9zrih1cK7p6NWisBg80aZSHSo4=,tag:4JpkXOhLHh/L9gIQMGFjRA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Y3XpcVoSLLvGmRJXiNYckmspK/135vyU/vCCepEALdVMv6NmSfO0,iv:PQtQb0at1hwALXwSJLOaU5Sx2nd2WJmKG4FJ0dXJGuo=,tag:BwCD2WoN8zjbMyf4/P4YGg==,type:str]
    #ENC[AES256_GCM,data:IW60qwj8qFvsS9K0cgtMXSevkPpsBKl2AAbRQhycEfTujKbi/qpFcRBNGJIfpDNML18C7JAjqhAW9CV6e6U3L112fPYsEUg=,iv:nuCguh2jcJG1xD7g1Ucdw6gnzaViAtgSB4lRCcE1rY4=,tag:C+5Uue6F9aRfk87tX70r7Q==,type:comment]
    #ENC[AES256_GCM,data:9fyxVrvcOnqYEIlMNPXsm7HqwQvcDQQ3UGeP6c5Rm0fUGUr0LD9dr3gYLzGKO5LDqT9CYYzL,iv:UjuIRY0bnW7IoNFCY6MWYGnpHVY8ZTy/ZWLBePfzV5I=,tag:6Jz67cPC279aoMAMQz+8Wg==,type:comment]
    #ENC[AES256_GCM,data:mA8HoR4rQaYEmfFtRB5XPwuGsCl73bGl1yvMbUEqaYi7ovw=,iv:qvOt2ZwcMKGMUYmgaq/yzeD3dUXjpjUX5NDCP0KlnV4=,tag:pQ0fcGUO0k3paQhvhvxFFQ==,type:comment]
    #ENC[AES256_GCM,data:NwMlNWVBuM34GGWcxutPUwpCWxgjtG/OV45WN4U/4ZlpjoioxzRe,iv:isyt8uSK3kNOUODiJovWRQBAHRyw4nh4ncpNOg3xvOc=,tag:XYH9jsSgvESCqg6NpcepOQ==,type:comment]
    #ENC[AES256_GCM,data:tivjLU2Qgzk1bsv+9C4=,iv:H9KDMAOHaLE07zKkPclmW9Gcs2zmIkt75aztxLTQzhw=,tag:GywLtkLwWJSZs12y9SEVag==,type:comment]
    PODNET: ENC[AES256_GCM,data:NTO/aQw7cyTADno+Mg==,iv:UwDZKu6v7cIXOgZDHz/hFvUlH/66aIGAEq3HKksVPYc=,tag:OfITJ9gRJOOptkaGLmfcJw==,type:str]
    SVCNET: ENC[AES256_GCM,data:QFGNH7nsTkxG8+IAGw==,iv:N+u9RIu7eeWUcwh5Dz8/ylH/HgNgQgmIgqWF4IHYruk=,tag:pvSGVGCAWZ7XKpYgeAlwiQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:5KaKFtEL7Bvasg/nZs3PBb6VY5Ss/TI=,iv:PRmKVNpdmPg6jH5OXq2EgsxAfjHT8IpVMJVLZ77PfoU=,tag:N4WCZ5L5WJFwWODgHbgo1Q==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:t3vzOd0U5LYGLYtY0yhpQ3Qr1ZVIoaIy5leC548G0TWLjOMYSZiXPg==,iv:T24iufkvEAbXoDGhc0lTu553Q3MwuCbxYThUBnNTifw=,tag:GDmUUCUplYaz/TpvBJnZJw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:5rezfkigvppIsQ==,iv:XpuQnW3VwGKGhuSsEbd98+Iu3v0MAscixsVoEpCEiio=,tag:TINV89G4KA5sFV3a5Dvj4g==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:fvpyK8v4/OugNVmK,iv:sfJOrA3mXKqj+NXC37oFXxjO4+Yy/UQ69fbLl7svHdk=,tag:X++dchAx09Vq2Ra/ZneRtg==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:J2mtunIZk+Aco0pc,iv:vfK6h4Y0Pejs/vGaXMqZbxiW7fACvEXKRS91kLDansk=,tag:KJq1XewsdmzOquSwSl0OYQ==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:bNuBvkE290aR+tZL/Q8TShvNxS5YyhK3,iv:iTAfvH890EaHKxSt7xoEqO5eCr7EB7/84ZnqoFrsWJ4=,tag:mIboHu2WimNNPs9z6WQ/Gw==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:PnObvqkfgh31CtlDEaD4QaeduVes+bph,iv:3t0DxQvoxO/NzyblKORu6V5rnfCl0fG5I0oK6KN+OQ8=,tag:7v+X8GUpfxo22KG6SPlwlQ==,type:str]
    S3URL: ENC[AES256_GCM,data:7PWD28dSNwLlDHrg8hEor6A3Bv6n3hrqrEyM7wqDqlnx,iv:nmcDOtIyX8dq0sLJtrJ1tWH2osMowqL/GRkbAIgbeAc=,tag:vPlP8oVYCB/M7CJAA7k7KQ==,type:str]
    S3PREFIX: ENC[AES256_GCM,data:yVLLbRlBwOjU1ym/LzKC8DXbMg==,iv:FCW1mXOaqEht6go9qYtNAMynUAYddbx4U+8C9emx5us=,tag:k+2a5+hKZPfx4I5JqWweAg==,type:str]
    S3ID: ENC[AES256_GCM,data:4rZ/BVFViv2auJ4lea2TNG8MtVUztqtH,iv:p8guW2IABP9P/V+x0R6TyCU88XDUxGJVSvA3uXFrEak=,tag:mwq854DvYAHaCWSOEgWepw==,type:str]
    S3KEY: ENC[AES256_GCM,data:qo0npB4bOJlwgJL9j6pZSUl554clI33p/R2r9mj5uFA/ZGk0Vlqnt25j,iv:DFEWiEr45losPBF/XyRcJ5uIeXP1VHRU3sSV3uEc0gk=,tag:+XLnK0tn2LvlUSYSAqu+4g==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:gQ+OzQ==,iv:d7i+mFiu5XQKyGKXjI5aPHoo/NUHl58CAvzovaoSl5Y=,tag:gBTGvbgwIodeu+NIjTEF1A==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10e04afnhnka5steqvjnug2zylp3ng0rjzv765pkv47c8megcg9hs8w7rdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVKzRQTCtXUEJuOUpSRitG
            anpmMFRRbnVqc1cxamFIa3NTVW1UYXh5d3c4Cis1YXpKZ0lxbm5yZ3o1RXpOQ2xY
            WXQ3dGFxQ004d0orMUVsVHNyNThEWEEKLS0tIFczSi9FWDdHbk1tSDRQcDQxY1dj
            MmlWVGdCRWROcnBLSjBLcnkzaTg3a28KByTsiVVHqSd3K1FuIThUN66mrzWb36lr
            9zt1B1j1tXkWT0gMvM/qyK0HpID4KHx5zRjVpGVYU9ujoOfUxDoASA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T20:25:12Z"
    mac: ENC[AES256_GCM,data:gxDHoqimWbzqB5KMFHUjMSJcwidoZv0Su83eaJDp40ioZAhkpqBUq1vVfr1akbwW+TEGULNzJ2YX0271cEdElF1phBp0YUEJYMrnenapen4rXD0ky9BzNLcagmuuP+h5Wh/WSE6xQFsYizqvJ/W5zeFShAasQ/Q/lmRbrYCSjHU=,iv:vy2Rlctw7qGN7gtDi8+ehFI4sMQt+8bj1lShSmjR/sc=,tag:YV0H3lav9QswsbGFsUbkuA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
