apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aQWRuG0be2SYSHkdvibPm7XUFXUs0eMluzutwMHG/9NDSt2JdjTtcNqWmkMFx+6zcfdsg741IgytVVM8Wnly6yyb9sz76LfkyxF+93XgWhq3SW00GI0NqMfxWOz4UfbKI9cpUY/VCKrcZAXlyWAJodNel9zJw7RX3LYYRBZyaH1PvJA8XHr0YpunxC7POT9oN0VomQmDTtYGNbpNQtcFGo3mpeFopIcU24PpWXq1OHdTw9U3/6PgD2eOoCEFa9fadnSCNQwg7Jd/2fuPeyHYfMRgcWIWr2TST5BqJm3TmiMoCN/6IaGe7gsb8kFWjmfiro8r0IsMOPUnVaU80+DX4XyPY9BBU+/GDXqLtAnULkwaNXNsndSI3oRmP55lWf5H,iv:kPliItmX3CLvYEyEzJx8wL3MaFgqXDwRvYABb4oyMcQ=,tag:SV57J+fk8yc9nCo8PZmojA==,type:str]
    identity.pub: ENC[AES256_GCM,data:6vZ720zZ5fGih3qTLFdUS/K2Ep3QrgrmpRCipkLzNmV8Ytt4NbePKYmyoVi19elkVbRWMAZYWwOVOAMxXeOeFAAkH+4IluEXQrln2Kx0KygaOv0E67P4ZF5ZjAWTq+dQbSFn9I7s/69GbgMVyXmCrsPXGTivo4Z9HZ39gD+YQCxrdnm/LBk+7/TFaj0vG/meyzsV6iEU46lFZnk2+Di1CQn2Ma7Ui8sozXv/UAO0R/NdrDH6a1vZusY3H0opgHS3SmKwI0tI2si8amfcHg==,iv:ystB8KPn/Q1HXTfKqd5cnz9Vm/GuAaTbeeHAeq13p6o=,tag:4Jev7WGkrYMSRk5Zh5dLpA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Qj/dFrJiIpPAA7a/udxUQ/iS5gBXVucjEBBnIGcOkywBQKiII/TtRnNWccIU5tDNIEp09ogJWucM0LZVbA82mtXeyxoKemVAiRhIq+c4QRydMIvUtl4phe0dnUiS39fCCyUUpPIX/7Hf7+47k2tavr9Tb/8CsiNd2KOV+waWAmCx2F5ypxUWv5v0IcP+h9QtcyY5CM/gWbUAYSgNYdSIJIkZkC7dWOwdorsY,iv:oEkXmZbEnf/ZIZtWqyfSo0j3VEOsAWw7oO850eMExCk=,tag:zS4MhEd7EHeJ/iprZdfvvg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10e04afnhnka5steqvjnug2zylp3ng0rjzv765pkv47c8megcg9hs8w7rdf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dnRuU0lFcGN1TTZDM0xn
            cXBmNlVHSVk3Wis1UjBDc2gwb3loNnBTTzJJCmhmZmV2UFEzamgyb1AzTDZ3L2x0
            dmtmT0FvMFBnbXNrMGhOMmRzbG8wWFUKLS0tIDJJOTNBRHhkd0RQM3g5amdRL0c3
            SXhOZjZacVBwZThmZ0FGSU1vUkIxY0EKgVSHgOlThwfK9Qw+WL4FtFI3A9OUh9Vk
            2L9jEYCP4MBthYsQnXIFiWXgLJ10KcyTHF6r2iochhFrJ6kMpdGvWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T22:15:08Z"
    mac: ENC[AES256_GCM,data:pWIkSt3y2Nkxx+sH1um5QNCcPn0YX6SF9YUX2o6WIfNKFNyU1evDnDjT/bGOr4H6t+rS9JoIWFfgCr4N8P7ztrWLRIeK+KguvoQZkK8VBrSUB9cu+kF+Ltk3I1PWvoUbrVi71SBB/tjS0QNopUN6889fkviZCd7G8WLy4WIhKd8=,iv:CtbAE1KhgLjor+bydtmDBD4zTmhBDKZzPGDpcw4lgsw=,tag:1hQo2oLt1mtHHI6ZjLN7mA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
