apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Wt1Goq96x703SXKIXJ/j29W+KHUFirUDCGH4rkVWcFl42hSHbdxwhcHULCsNivREMjjgGm9AlgFxGn4aB9IJAlRyrS7g4Te6vk+VgGH3cgf/3ooTonRlglhOqLzjlKFT3cE1CVOYF0AhYhse71Yu6Uy9hbyFNsFah4XsnF0GeuO54ufWppLZXs1Cw6HxPtTfaN+yIc9v+RBFVvhX0rsBfBbY1LtPUSDZ+911XqVPcq6LpHn8GvEy/V0LBEbGJAPCU7pC4jnEN/qV1l2zk2xH9LjZ+3eatJOBjK3zrsPqtG4pLKpuUpDbTZmb49CkCSveN/Mqfca9jP250Zxzv1/i+bA1O9pd0MEnVS0tV2Y3b8GtkDpEXOuTIahE/gn/+h8J,iv:c75R8BaAs/ZyJdsY3xBoURUw5LQFaUC5AfuZl7aHY+g=,tag:u3mz7B6iXFmUzLPDRAtWdA==,type:str]
    identity.pub: ENC[AES256_GCM,data:b8ZJpqMVy2xweYsv8lE5GWfIgdVezNkboqOXIHjmUptgQeS+ZWxzG1gXxo2cqQZ0iEjAsKfeXEls/803DO1okl/HsCrYUOqf7EwpEXEqm5m6iJsa0ZcxNVKcxbiZesXpfXWJPq5MPrZvD5YhNON+Vw+KCy+1YtyPTj0ZIcXVW8QM9Hyy2gMB+pBop0Kl6iEKyoLTfkdaKmNKDPyANKMs/llmBqEFcX0AL/55p7Zg7jEqIa/KOHz1S0jr/aEpkJXLaXJF0KD2Y4RtvelcMA==,iv:ByCj4/LPO8yB6OMfE6VIlgfSLUh3Z3o/mFU+HVJnoH4=,tag:X+XucODMelO7RVlu8hU/xw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Y/xzXrdRllVAm/TD8V9qBVS9rpY6FYkv1OZvdWsvRCOKwjWkTlB6dtTqGLlYctgcBVLiBYN/1m0vv44Fu+CZc1G4us3WIuPGAn4ijt8tUUgBJ0qjGFkuqZoMhlNBnBM7bHMe6XGW7gngyZKihIRuFTylFN6TEGKRSNH0t8ps2VxgQOTrQR1PEYn/uciUrb+TSeQNDMZPq1i0QCoZ+SNdnBIwW/2Qr0IDbpnr,iv:eRz6VMRKQqgzKX9NY5c+qlxT77adDs3Q5QellpODRjY=,tag:rl8ypuJFh+EoU3o6/W7+pA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVGo1c2xhTTVjNkJsc1A2
            dkJTaS9SQTkxZExlOWMzTVNQSFhoR0xuaGk4Cm1qU3c1UzRKenpzbVhKVlVveUw4
            b2t6M1A0a1VERm5lb2Z6STMrR3ZtVXMKLS0tIDBscUZ2eGM2Q1RZeUZoOEtleUNz
            NE5rbTR1OWV1S2VFYUxjcExRV0N5cGMKH4U6A4kgjfWMRBdUDLTjmSg89gXs7wsQ
            x74YhkhSf4bNlGwmRVk95cGNarQhvRe7DDQpV0iMBZBmCURl41qWCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T13:02:17Z"
    mac: ENC[AES256_GCM,data:IrindkFoB5EZQ/+IWJNP0PxowTkQDKzBV4BV2Po4cYu0lByy9kqW7Vm1+3ThIp/orxBBzKKC30JjN7dhzp/GFb5zYi6ZLrqT3iT8mmvl8ZxjO6/gAJWKoCXjzMPbNPf10bJkmkxwITh7hEc3thsLGWsq93wrgihdQhuwjB6xD30=,iv:CAgPEY3bEB+rYewjcMZlpDHHGHOE0depFizR4weNgoo=,tag:EVhBK/bTm4Hfme8edLxM6g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
