apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:orMrxKbNPXvdzQaPQ1JNoZf4Re0Y4nernDks146nQ9lhw1gMMHiPaqkRIbcFN+wzTttomDS2CxO5sfiXISCHhn98OWmNrKr56PhKiV/NQe2GJfqcV4gcUVwjv/MX7bVfI4UDDeUHFpPvT7Xn+/Eesgh/UR7UaHPfpcWdBcmsr3Yu5RLLFN0ASDulvkt9Il24suJW1cb6+06aN5F7bjG1wT55q8KJNidk1qicYJN/UBQNFoCbmgxxHgy8YXH3ErK70+3MS0mMTGHW1vgoxEtYWmUfejxCZZ7W7NUUQXl4UNpjgUQ+p/qKMbuvsBzgZHOqRf9+ztOL7fk52nj1nW8qfyMroeGZEzjnoxOnHDW6dJAdWblGa2i9AiGMZnYnCkPT,iv:4salr/gOw7BgccOmt0C4TNGWR5AcbJnhlmf1JWCsOtw=,tag:4WYzRJJPYjPTyWJ6sI6BZg==,type:str]
    identity.pub: ENC[AES256_GCM,data:XrpIpc5vJmJgNDmAzdOR1ONj+/s9Z/Ic9RmuunWZmaD0rO3vCBor5D0+afnto6E6gYjrvrEvnpovyTX1MdL8+MmWEYEdYfQcjXye7CKKc6gwHECcRr9eXpGs96B6Ia7sgwSsN5e4rykH8hmwG69vQi5ZstZ+U9rX3EbuJJRNg98GDiQMDYQqn2nj/7/yN/F+HVs401mwcxAdfkuUL9Mzqrip+rA+Mt4Oxc/ULz969/Oz6BTDAItOFEdjqhx4yv9dIXTHl9RxzSLGeWfqpg==,iv:wz+8VpNpjDasyQY8LQ3RPCn6pEIwLoJbbGAWs3L42yA=,tag:JiuDnwjcrcPUn2nZdWuJtA==,type:str]
    known_hosts: ENC[AES256_GCM,data:rd+GbvZdxKxiCHBCc2ENgLn+AjXAsc5G/LcpcRUycrBhnZLn4NiOrM8lDRZq01IwH8RqtZdYCEoh3P6/njRYfPHwUzYU9io8Dn8iYTA6C/Xe0f+oY+2oRLb89m2zoY0cRTvBH22U1IhrmYE7V+7l82WYBepC7sFr4mNbrxJakwD1/LqX5lmLqp+qjqd6sD1VahabfIzeD95C9UIMNn+IOtr0n5/mxazsTTZy,iv:6W0oO68ZSyJBLURUFM86GwzYGIWmEBacjOCQN+uoRYw=,tag:HiD5vob0FPoW3AxSt195Eg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1dp29elpmucy5dn8tqh60ezrymky9fu9v3mnhccyxsxs3guhg4qmqdwj7n4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZmEyRXJ3MCt2a2tmSHBm
            UUtoQjdjR2htUjN2VjBqNFZyWHkyN2NJejA0CnU4Zjkvd3RMQmZEelAyd3I2NEI4
            UVMwUlZwTmV5K1dNSHFITmdBcDRyUncKLS0tIDd5d2pEMkRRUXdsdHFIVStVVE0v
            K2hVZDZQR1F1dThxU3pKcWxlZ0hieGsKH5tMvAivLNzYpPqJKzvxuYCqsxlFikBc
            HyyHBhMShN5q8u3C4o/f3fhZO+d7HRmM+g0XgmM4CGfZaWVnlF7cDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T08:17:52Z"
    mac: ENC[AES256_GCM,data:tfoH7spmXMRVJYp/rPVodCogV9ZKr/trum5jvkmL6Yj5Ujr6iBlRPIBOgZT1E+uy4aLo9XcorA+Y0uPDdp3s1mxZwq3gA6ySHi4FXPps9B4ayuBQ6dNId95tGNCgANUl0jNq5FCika1wVbIqek+/8n7CMmWfJ0xVpWkmSO+1lAo=,iv:VX7TyRWIyZeQzjpqJ8jsZw4A3tRJ2ugZn+YGsVrjhrI=,tag:L+bhZZsM06ZSRmcbnxlf/Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
