apiVersion: v1
kind: Secret
metadata:
  name: deploy-key
  namespace: flux-system
stringData:
  identity: ENC[AES256_GCM,data:FW+qDaBF2jt4AyGYJUug8uPwdrdJZcmv49ycRRlIhLMQVBDdfdNTgRrBUdS6jgjeQ0zu3XNnysU7h5nvF9I/zOCVTaetS9oMF/B1ccLJuuOLpCNipK3+hdBiZxwWqpH8qvgi1BlxfH4mGLAMD6CpGC8UNffvJhpczi39FZ83pefVFnf1TFY3vENRcdNq/dNMHHq7buNPb7aM+idxbAkGyQPgNc0CntBfGnlBMQmw0NsX565IWvJ9zN/0Bl+wf2OqI77Ye+pGqx981o20OF3H7V73jxT580eAPpSWtE0uwymBLrAaeXywIguFdLeIAwbhbuNSMAj/FXuf9WAKCMKtRsi+8T5Dz6YvwhPavvnWGpea21wEDBh/IzQ7tAriq9G1,iv:242UVxmRE5osIKvLGfpXJZvtBKa6aenojkK4+ru0Hno=,tag:OSItimm5ljluGybynuvxRA==,type:str]
  identity.pub: ENC[AES256_GCM,data:fpQElfzU3v6t7cSCEepMm5mmD9QUGQHupJ4g0A9AV28KSbxa8ngDgdvcssszSE4f+DZm2HH7GUaNPBoQxRhtvGWmFeN+uY/5/zRSA/gSomv+YvDkBbP0oWHCezEs5DyEZNub5Y5Q5AvhfPE4/ed2e7dAO/7W9GO+ObpisEDugF1VyWHimXDlb5jE0mZoYRaYp0hGYhDP39i8oW+U/3oKSiRebDde3IPu4mk0ZEY4Yp5ad4brkV9f/OE3u0o1lBgyWFWrezOzi42gpud9Vw==,iv:xLP0ZJ/Hj5xCsJFEdy+XBlsa/z8GhbTzHaIfjJfgN5Y=,tag:sz+aIW7Y3AXcvsxqZy276w==,type:str]
  known_hosts: ENC[AES256_GCM,data:TVxURpHeGPmf0C9/5WWDsLjfW6qqqqvOoT9ljNFd6kqQJPrClK0K0zEWTvc5vWuzCPt830ofDS2mjANt4CW/WHg34/GcAOAwfzMKevZCJ+xJPeTPa+Mbe4OHLFe+z31PjN9rqFyEMMSr8p36wOtR7jyuc0jctkm1K5wj866tMbBdkexPJ+qpa1bP+PfEldiUM+RE82bdhdjARITK1El9eQrxDcE8fbP8w45T,iv:R8Vvg7oMCXmWXtcW/X7HJMgPvd/zYp15GcMH2Su6xFg=,tag:mkAjLYhFGxsZ5PE/NrJUhw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UEE3KzJFZEUwNFZMazBQ
        NUprSVVOU1kyWklYTTNQWlJsU0NiVWN6eHlrClppNWhYUTFVVjdoUFpwQzhTL0Fu
        Nzc4WFJLZVlVTENOVTFySVBtNEUyb3cKLS0tIEZXb0VnMlZ3MXJiem5laVlndjJU
        UklLYkkwL2NwUnIrWmpDWWZmUnF4cWcKJG5EJBJZeHFwDwtJY0AaytqbOGMHSzWQ
        IUdYUA5/TjKyJrzD3+GzzuggufsNLeGAsHxFeK+EiSqYyESp3cEyFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jqaxewhvdms0a4xnzz2frg4ywc8ll3wy7pyyqye7v2eddwwf298qpcm4hp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T07:49:52Z"
  mac: ENC[AES256_GCM,data:2prKaxo9jSEXKebZvHP0yjHBWD5Qe9y7Opov1IDXIFjX3FwDxh0M+3hGCgTgcvfGU2nRMtxFgquYgjkbn5nXWJyWcX4ETvL9m/KRY2hDF5XaNzgaBBZJmBQ02kCNF13H/KA4jpjMt7nZsAnjmfnDx7MkNMj7kEiLuaWwnP9wyHk=,iv:fQamsIOzdQF/dk0leEFJNPWNY2Ihdqhv8Ga9yEXytpE=,tag:52E5PrqQr0kDT22wwnU1Vg==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
