apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  age.agekey: ENC[AES256_GCM,data:4okLNN2utQRJaExl+gkNb2vXiWAtUbzk4ZsnDF2M+xmD3+h+vKg6RmrAbji7eHRYD1viEkUyM6TWShbka8fvHkCyIOY1AQY8JUg=,iv:YLuj33kapnuKRek20qtQK85D7brASGSPmO6qmqpk/H0=,tag:G7abZDNOP7UARmKeOkSXhQ==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNGVHUWcvTXB1VE9xU203
        dlZDU2JRQXVjZUMraFJnc3RNOG1BVmZOUmw4Ck5FOTlicC94SFk0K1VLS0loZ2NT
        VStxb0Z3UnZmZ2hqYkNodzY4U2xZZ0kKLS0tIFJmWkRocGJ3ZndXU3kzSGliaEV6
        MktGV3Q0SDFDR0xtaDIvNmlETnJjencKZOP/rzacQkj2f2ySvXcoxOkD5p3a7CIz
        lYQPM6P5Jw9CVCA9TpmLHQp3gMgHagAS8rT0s/y1dLa7d/Qfd+vSCg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jqaxewhvdms0a4xnzz2frg4ywc8ll3wy7pyyqye7v2eddwwf298qpcm4hp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-30T07:49:52Z"
  mac: ENC[AES256_GCM,data:xsLy4nQ7Pbkxu8+39R77ULyWZV7yLjlqPKStz6/xwm6BSsodFKH9xjXL0xv+cNlAHIZ5t6kNOSA6ZLpxibTa927LhWtWL5BInLuQY7Psk+snOeO6YRy6GcQ5NRWOwb4Y4gCPqfwZjlYu55t061gy7OzTs/FaVN8HYw4TUwIqIUc=,iv:QnZNKW6aYuCLoCbhKzAMdJ1GEy5mplYpyFxieiyfXxY=,tag:sTU55B91HwpbMuz1kSos9w==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
