apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
stringData:
  age.agekey: ENC[AES256_GCM,data:VetHL/EGCKNh9a0zRSl2qHPKkAqu9ico9hbnYwpE8qqwc+h/adigrdKs2aiGHNmxkIr6XIR6KWqfAEkX9xwGuGBO4OsFz0IYO1Y=,iv:47Ks5AO9i8fLPl+eACQPd87pdJGtK1SpOVtHfmA2uPc=,tag:pUvwUop+/3IdVkE+UNGTbw==,type:str]
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WHpkYzlCazZiY1J5bHpV
        T2U4eER6cyt4TEd0OWMyMUNuOGdzWHg4OVI4CmswUnlMUXRoNnZEOTdqV2RkczZN
        dllIbXFFU25IMnVTS1FZOHR0UUg1MXcKLS0tIG0wVzZkc0ZRVk9DRmptMmY0N01z
        OW1hQm9aVjNoN0lmMnV5V2l3WDNFdU0Kw4NqahV/zVS8hRxcqnx05T5plFAqKxus
        1ekl/EUrk6RZcOyNvdfWgeSDOC8/1vdZ2VQIg81BLXm3CLF9VlubZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jqaxewhvdms0a4xnzz2frg4ywc8ll3wy7pyyqye7v2eddwwf298qpcm4hp
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-29T19:16:23Z"
  mac: ENC[AES256_GCM,data:aqi9X+rbwAkQ6AjBZjEUw7aOUS9egsK7gCRgMihUX9nYEzprjxgGFiFTCzUamOIbgTYNGXglWT05eEF9nsZevPa1XIvg+o0I24jwyA8oWtlXHPXb+5PcUexMDaV6I5c/ML+lmDQ97iwzmG+uMRBR/3LqMBzS8ktpuJdBQH9Rp84=,iv:4rrNreKCb0AVMvu0tGN2DQrfzReRVoR9/c5HsRrREZw=,tag:qJkXtDEK4dA5GLmn3FNcbQ==,type:str]
  mac_only_encrypted: true
  shamir_threshold: 3
  version: 3.13.3
